services:
  postgres:
    image: postgres:16
    container_name: control_pago_db

    environment:
      POSTGRES_DB: control_pago
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: